openapi: 3.0.0
info:
  title: OpenAPI document for HollyWorksDays Challenge.
  description: How many days we works on a bank.
  version: 1.0.10
paths:
  /api/v1/workdays:
    get:
      summary: Get the whole works days and holly days of a year.
      description: Retrieves the year of and the number of seeds holly days.
      parameters:
        - name: yearOf
          in: query
          required: true
          schema:
            type: integer
            format: int8
        - name: numberOF
          in: query
          required: true
          schema:
            type: integer
            format: int8
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                minItems: 2
                maxItems: 2
                items:
                  type: string
        '400':
          description: Invalid query Params
        '404':
          description: Service Not found
        '500':
          description: Exception Error
